# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-27 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0002_auto_20201127_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=255, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryDocumentCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='ContactDetailsLogDocument',
            new_name='FeeWaiverLogDocument',
        ),
        migrations.RenameModel(
            old_name='ContactDetailsLogEntry',
            new_name='FeeWaiverLogEntry',
        ),
        migrations.RenameModel(
            old_name='ApprovalUserAction',
            new_name='FeeWaiverUserAction',
        ),
        migrations.AlterField(
            model_name='feewaiverlogentry',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='feewaiver.FeeWaiver'),
        ),
        migrations.AlterField(
            model_name='feewaiveruseraction',
            name='contact_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='feewaiver.FeeWaiver'),
        ),
        migrations.AddField(
            model_name='temporarydocument',
            name='temp_document_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='feewaiver.TemporaryDocumentCollection'),
        ),
    ]
