# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-27 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0003_auto_20201127_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feewaiver',
            name='contact_details',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fee_waiver', to='feewaiver.ContactDetails'),
            preserve_default=False,
        ),
    ]
