# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-27 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0004_auto_20201127_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feewaiver',
            name='number_of_vehicles',
            field=models.IntegerField(default=0),
        ),
    ]
