# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-30 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0005_auto_20201127_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='feewaiver',
            name='lodgement_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
