# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-30 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0006_feewaiver_lodgement_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feewaiver',
            name='lodgement_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
