# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-30 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0007_feewaiver_lodgement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feewaiver',
            name='lodgement_number',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
