# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-04 03:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feewaiver', '0012_auto_20201203_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproversGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Approvers group',
            },
        ),
        migrations.CreateModel(
            name='AssessorsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Assessors group',
            },
        ),
    ]
