# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-07 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0013_approversgroup_assessorsgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeWaiverVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('date_from', models.DateField(null=True, verbose_name='Date from')),
                ('date_to', models.DateField(null=True, verbose_name='Date to')),
                ('number_of_vehicles', models.IntegerField(default=0)),
                ('age_of_participants', models.CharField(blank=True, choices=[('15', 'Under 15 yrs'), ('24', '15-24 yrs'), ('25', '25-39 yrs'), ('40', '40-59 yrs'), ('60', '60 yrs and over')], max_length=100, null=True, verbose_name='Age of Participants')),
            ],
        ),
        migrations.RemoveField(
            model_name='feewaiver',
            name='age_of_participants',
        ),
        migrations.RemoveField(
            model_name='feewaiver',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='feewaiver',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='feewaiver',
            name='fee_waiver_description',
        ),
        migrations.RemoveField(
            model_name='feewaiver',
            name='number_of_vehicles',
        ),
        migrations.RemoveField(
            model_name='feewaiver',
            name='parks',
        ),
        migrations.AddField(
            model_name='feewaivervisit',
            name='fee_waiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='feewaiver.FeeWaiver'),
        ),
        migrations.AddField(
            model_name='feewaivervisit',
            name='parks',
            field=models.ManyToManyField(to='feewaiver.Park'),
        ),
    ]
