# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-07 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0014_auto_20201207_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='feewaivervisit',
            name='camping_requested',
            field=models.BooleanField(default=False),
        ),
    ]
