# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-08 06:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0015_feewaivervisit_camping_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feewaivervisit',
            name='age_of_participants',
        ),
        migrations.AddField(
            model_name='feewaivervisit',
            name='age_of_participants_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('15', 'Under 15 yrs'), ('24', '15-24 yrs'), ('25', '25-39 yrs'), ('40', '40-59 yrs'), ('60', '60 yrs and over')], max_length=100), default=[], size=5),
        ),
    ]
