# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-09 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0018_feewaiver_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feewaiver',
            name='processing_status',
            field=models.CharField(choices=[('with_assessor', 'With Assessor'), ('with_approver', 'With Approver'), ('approved', 'Approved'), ('declined', 'Declined')], default='with_assessor', max_length=30, verbose_name='Processing Status'),
        ),
    ]
