# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-09 08:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feewaiver', '0019_auto_20201209_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='feewaiver',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feewaiver_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
