# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-10 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0020_feewaiver_assigned_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetailsdocument',
            name='contact_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='feewaiver.ContactDetails'),
        ),
    ]
