# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-14 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0023_feewaiver_comments_to_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='feewaivervisit',
            name='camping_assessment',
            field=models.CharField(choices=[('', '-----'), ('child_rate', 'Adult camping fees at child rate'), ('full_waiver', 'Full camping waiver')], default='', max_length=100, verbose_name='Camping Assessment'),
        ),
    ]
