# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-16 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0025_auto_20201216_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='feewaiver',
            name='proposed_status',
            field=models.CharField(choices=[('issue', 'Fee Waiver'), ('concession', 'Concession'), ('decline', 'Decline')], max_length=30, null=True, verbose_name='Proposed Status'),
        ),
    ]
