# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-21 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0026_feewaiver_proposed_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feewaiveruseraction',
            options={'ordering': ('-when',)},
        ),
        migrations.AlterField(
            model_name='feewaiver',
            name='processing_status',
            field=models.CharField(choices=[('with_assessor', 'With Assessor'), ('with_approver', 'With Approver'), ('issued', 'Issued'), ('concession', 'Concession'), ('declined', 'Declined')], default='with_assessor', max_length=30, verbose_name='Processing Status'),
        ),
    ]
