# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-21 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import feewaiver.models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0027_auto_20201221_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeWaiverDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=feewaiver.models.update_feewaiver_doc_filename)),
            ],
        ),
        migrations.AlterField(
            model_name='feewaiver',
            name='processing_status',
            field=models.CharField(choices=[('with_assessor', 'With Assessor'), ('with_approver', 'With Approver'), ('issued', 'Issued Fee Waiver'), ('concession', 'Issued Concession'), ('declined', 'Declined')], default='with_assessor', max_length=30, verbose_name='Processing Status'),
        ),
        migrations.AddField(
            model_name='feewaiver',
            name='feewaiver_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feewaiver.FeeWaiverDocument'),
        ),
    ]
