# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-21 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0028_auto_20201221_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='_file',
            field=models.FileField(blank=True, null=True, upload_to='feewaiver_template'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(choices=[('feewaiver_template_file', 'Feewaiver template file')], max_length=255),
        ),
    ]
