# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-22 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0029_auto_20201221_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='email_confirmation',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
