# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-22 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0030_contactdetails_email_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feewaiver',
            name='feewaiver_document',
        ),
        migrations.AddField(
            model_name='feewaiverdocument',
            name='feewaiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='feewaiver.FeeWaiver'),
            preserve_default=False,
        ),
    ]
