# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-29 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0033_campground'),
    ]

    operations = [
        migrations.AddField(
            model_name='feewaivervisit',
            name='campgrounds',
            field=models.ManyToManyField(to='feewaiver.CampGround'),
        ),
    ]
