# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-04 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0035_feewaivervisit_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='feewaivervisit',
            name='number_of_participants',
            field=models.IntegerField(default=0),
        ),
    ]
