# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-05 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0036_feewaivervisit_number_of_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='entrance_fee',
            field=models.BooleanField(default=False),
        ),
    ]
