# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-05 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0037_park_entrance_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='feewaivervisit',
            name='free_parks',
            field=models.ManyToManyField(related_name='feewaiver_free_parks', to='feewaiver.Park'),
        ),
    ]
