# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-19 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import feewaiver.main_models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0040_auto_20210113_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeWaiverWordTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=feewaiver.main_models.update_feewaiver_word_filename)),
            ],
            options={
                'verbose_name_plural': 'Fee Waiver Templates',
            },
        ),
    ]
