# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-19 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0041_feewaiverwordtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feewaiverwordtemplate',
            name='name',
        ),
    ]
