# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-19 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0042_remove_feewaiverwordtemplate_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feewaiverwordtemplate',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Fee Waiver Templates'},
        ),
    ]
