# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-28 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0044_delete_globalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
