# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-08 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import feewaiver.main_models
import feewaiver.models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0045_auto_20210129_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetailsdocument',
            name='_file',
            field=models.FileField(max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='feewaiverdocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=feewaiver.models.update_feewaiver_doc_filename),
        ),
        migrations.AlterField(
            model_name='feewaiverlogdocument',
            name='_file',
            field=models.FileField(max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='feewaiverwordtemplate',
            name='_file',
            field=models.FileField(max_length=255, upload_to=feewaiver.main_models.update_feewaiver_word_filename),
        ),
    ]
