# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-08 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0046_auto_20210208_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='feewaiver',
            name='finalised',
            field=models.BooleanField(default=False),
        ),
    ]
