# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-23 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feewaiver', '0047_feewaiver_finalised'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='cc_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
